"""NotebookLM 适配层真实环境验证脚本（一次性 / 冒烟测试）。

流程：建测试 Notebook → 上传自生成的最小 PDF → 提问 → 校验回答非空 → 删除 Notebook。
用途：
    1. M2 交付后的真实环境验证
    2. notebooklm-py 依赖升级前的冒烟测试（设计文档 §7 风险缓解）

运行：.venv\\Scripts\\python scripts\\verify_notebooklm.py
消耗：1 次 chat 配额（免费版 50/天）。无需课程资料。
"""

from __future__ import annotations

import asyncio
import sys
import time
from pathlib import Path

# 允许以 python scripts/verify_notebooklm.py 直接运行
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from loguru import logger

from modules.config import load_config
from modules.file_manager import CourseFile, CourseManifest
from modules.logging_setup import setup_logging
from modules.network import setup_proxy
from modules.notebooklm import NotebookLMService

PDF_TEXT = (
    "Maxwell Equations Study Note. "
    "The Maxwell equations are the fundamental equations of electromagnetism. "
    "They describe how electric and magnetic fields are generated by charges "
    "and currents, and how they propagate as electromagnetic waves. "
    "Gauss law, Gauss law for magnetism, Faraday law and Ampere law with "
    "Maxwell correction form the complete set."
)


def minimal_pdf(text: str) -> bytes:
    """构造单页 Helvetica 文本的最小合法 PDF（xref 偏移动态计算）。

    PDF 标准字体不含中文，故正文用 ASCII。
    """
    content = f"BT /F1 12 Tf 72 720 Td ({text}) Tj ET".encode("latin-1")
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
        b"<< /Length " + str(len(content)).encode() + b" >>\nstream\n" + content + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    out = bytearray(b"%PDF-1.4\n")
    offsets: list[int] = []
    for i, obj in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{i} 0 obj\n".encode() + obj + b"\nendobj\n"
    xref_pos = len(out)
    out += b"xref\n0 " + str(len(objects) + 1).encode() + b"\n"
    out += b"0000000000 65535 f \n"
    for off in offsets:
        out += f"{off:010d} 00000 n \n".encode()
    out += (
        b"trailer\n<< /Size " + str(len(objects) + 1).encode()
        + b" /Root 1 0 R >>\nstartxref\n" + str(xref_pos).encode() + b"\n%%EOF"
    )
    return bytes(out)


async def run_verification() -> int:
    cfg = load_config()
    setup_logging(cfg.paths.logs_dir)
    setup_proxy(cfg.network.proxy)

    title = f"CourseLM-验证-{int(time.time())}"
    pdf_path = Path.cwd() / "output" / "_verify_sample.pdf"
    pdf_path.parent.mkdir(parents=True, exist_ok=True)
    pdf_path.write_bytes(minimal_pdf(PDF_TEXT))
    manifest = CourseManifest(
        course_name="验证",
        root=pdf_path.parent,
        files=[CourseFile(path=pdf_path, size_bytes=pdf_path.stat().st_size, category="pdf")],
        total_size_bytes=pdf_path.stat().st_size,
    )

    nb_id: str | None = None
    try:
        async with NotebookLMService(
            upload_wait_timeout=cfg.notebooklm.upload_wait_timeout,
        ) as svc:
            logger.info("步骤 1/4：创建测试 Notebook「{}」", title)
            nb_id = await svc.create_notebook(title)

            logger.info("步骤 2/4：上传最小 PDF（{} 字节）", len(PDF_TEXT))
            report = await svc.upload_sources(nb_id, manifest)
            if not report.uploaded:
                raise RuntimeError("上传失败")
            logger.info("上传成功：{}", report)

            logger.info("步骤 3/4：提问（等待回答，可能需要 30-120 秒）...")
            t0 = time.monotonic()
            answer = await svc.ask(
                nb_id,
                "What is the main topic of this document? Answer in one sentence.",
            )
            elapsed = time.monotonic() - t0
            if not answer.strip():
                raise RuntimeError("回答为空")
            logger.info("获得回答（{:.0f}s，{} 字符）：{}...",
                        elapsed, len(answer), answer.strip()[:120])

            logger.info("步骤 4/4：清理测试 Notebook")
            await svc.client.notebooks.delete(nb_id)
            nb_id = None

        logger.success("验证通过：适配层在真实环境工作正常 ✓")
        return 0
    except Exception as e:
        logger.error("验证失败：{}: {}", type(e).__name__, e)
        if nb_id is not None:
            logger.warning("测试 Notebook 未清理（id={}，标题「{}」），请到 NotebookLM 手动删除",
                           nb_id, title)
        return 1
    finally:
        pdf_path.unlink(missing_ok=True)


if __name__ == "__main__":
    sys.exit(asyncio.run(run_verification()))
